### ISSUE TITLE
New Logo Design For jxvideoplayer

### ISSUE THREAD

**Issue by somratking420** [longjianjiang/JXVideoPlayer#1]
hi @longjianjiang, im a graphics designer, after I review your project, the current logo does not look modern and interesting. I want to contribute by creating a new logo for your project and you do not have to pay for this because it's free. What do you think?

**Comment by longjianjiang** [comment]
sure, thank you! but right now this project didn't have a logo.

```
the current logo does not look modern and interesting
```

so i don't know where the `current logo` you saw is.

**Comment by somratking420** [comment]
ok sir,this is logo ready
